eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    hostname: localhost

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

app:
  service:
    authentication-service-url: http://skyhawks-authentication-service/v0.1
    notification-service-url: http://skyhawks-notification-service/v0.1
    school-service-url: http://skyhawks-school-service/v0.1
